import { Geist, Geist_Mono, Fredoka } from "next/font/google"; // Fredoka_One ki jagah Fredoka
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ScrollBanner from "./components/ScrollBanner";
import { FilterProvider } from "./context/FilterContext";
import { CartProvider } from "./context/CartContext";
import { UserProvider } from "./context/UserContext";
const fredoka = Fredoka({
  weight: '400', 
  subsets: ['latin'], 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fredoka.variable} antialiased`}
      >
        <FilterProvider>
          <CartProvider>
            <UserProvider>
              <ScrollBanner/>
              <Navbar/>
              {children}
              <Footer/>
            </UserProvider>
          </CartProvider>
        </FilterProvider>
      </body>
    </html>
  );
}
